name: attedance
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  firebase_database: ^10.2.4
  google_maps_flutter: ^2.4.0
  permission_handler: ^11.0.0
  geolocator: ^10.1.0
  maps_toolkit: ^3.0.0
  fluttertoast: ^8.2.2
  swipeable_button: ^0.2.0
  excel: ^2.1.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_background_service: ^5.0.1
  flutter_background_service_android: ^6.0.1
  flutter_background_service_ios: ^5.0.0
  flutter_local_notifications: ^15.1.1
  rive: ^0.11.17
  swipeable_button_view: ^0.0.2
  loading_animation_widget: ^1.2.0+4
  slider_button: ^2.0.0
  firebase_messaging: ^14.7.0
  http: ^1.1.0
  timer_count_down: ^2.2.0
  imei: ^0.0.1
  device_information: ^0.0.4
  firebase_auth: ^4.11.1
  pie_chart: ^5.3.2
  fl_chart: ^0.64.0
  dotted_border: ^2.1.0
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  firebase_storage: ^11.4.1
  firebase_app_check: ^0.2.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: postnobillbold
      fonts:
        - asset: assets/font/postnobillbold.ttf
    - family: postnobillextrabold
      fonts:
        - asset: assets/font/postnobillextrabold.ttf
    - family: PoppinsBold
      fonts:
        - asset: assets/font/PoppinsBold.ttf

  uses-material-design: true
  assets:
    - assets/images/
    - assets/riv/
